name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.34.0/conftest_0.34.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.34.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Create Workflow Context File
        run: |
          echo '{"github": {"actor": "'${{ github.actor }}'"}}' > workflow_context.json

      - name: Run Conftest policy check
        run: conftest test workflow_context.json --policy policy/github/rbac.rego

      - name: Fail if Policy Check Fails
        if: failure()
        run: exit 1

      - name: Terraform Init and Plan
        if: success()
        run: |
          terraform init
          terraform plan
