name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.34.0/conftest_0.34.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.34.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin

      - name: Install OPA
        run: |
          wget https://openpolicyagent.org/downloads/v0.40.0/opa_linux_amd64_static
          chmod +x opa_linux_amd64_static
          sudo mv opa_linux_amd64_static /usr/local/bin/opa

      - name: Create Workflow Context File
        run: |
          echo '{"github": {"actor": "'${{ github.actor }}'"}}' > workflow_context.json

      - name: Run OPA Policy Check
        id: opa_check
        run: |
          result=$(opa eval --format=json --input workflow_context.json --data policy/github/rbac.rego "data.github.rbac.allow_plan")
          allowed=$(echo $result | jq -r '.result[0].expressions[0].value')
          if [ "$allowed" != "true" ]; then
            echo "User is not authorized to run Terraform Plan."
            exit 1
          fi

      - name: Run Conftest Policy Check
        run: conftest test workflow_context.json --policy policy/github/rbac.rego

      - name: Terraform Init and Plan
        if: success()  # Only runs if both OPA and Conftest pass
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform plan
